#!/usr/bin/env bash

set -e

if ! [ -f .env ]; then
  echo "Please fill your docker credentials on .env file"
  echo "DOCKER_USERNAME=" >> .env
  echo "DOCKER_PASSWORD=" >> .env
  exit 1
fi

docker-compose -f ./sandbox.yml pull
docker-compose -f ./sandbox.yml run --rm sandbox
